# Unique project identifier and metadata
sonar.projectKey=prasadhire_GoCart-DevSecOps-Production
sonar.projectName=GoCart-DevSecOps-Production
sonar.projectVersion=1.0
sonar.organization=prasadhire

# Path to the source directories (relative to project root)
sonar.sources=app,components,lib

# File encoding
sonar.sourceEncoding=UTF-8

# Exclude generated code, dependencies, public assets, and infrastructure from scanning
sonar.exclusions=node_modules/**, .next/**, out/**, devops/**, public/**, **/*.test.js, **/*.spec.js, postcss.config.mjs, next.config.mjs

# Quality Gate requirements
sonar.qualitygate.wait=false
