apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  # Replace with your 16-character Gmail App Password (Settings -> Security -> App Passwords)
  gmail-app-password: "yjurjwrtwdppwuur"
